name: Update Submodule

on:
  workflow_dispatch:

jobs:
  submodule-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set git-config
        run: |
          git config --global user.name "jaotan"
          git config --global user.email "34743289+jaotan@users.noreply.github.com"

      - name: Get current date
        id: date
        run: echo "::set-output name=datetime::$(date +'%Y%m%d-%H%M%S')"

      - name: Create new branch
        run: hub checkout -b update-submodule-${{ steps.date.outputs.datetime }}

      - name: Update Submodule
        run: git submodule update --remote --merge

      - name: Create pull request
        run: |
          hub add -A
          hub commit -m "feat: Update submodules"
          hub push --set-upstream origin update-submodule-${{ steps.date.outputs.datetime }}
          hub pull-request -b master -m ""feat: Update submodules (${{ steps.date.outputs.datetime }})" -r ${{ github.event.sender.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
